from app.api.routes import (
    accounts,
    auth,
    car_goal,
    chat,
    companies,
    information,
    investment,
    market,
    model_recommendations,
    orders,
    portfolio,
    strategies,
    strategy_recommendations,
)

__all__ = [
    "accounts",
    "auth",
    "car_goal",
    "chat",
    "companies",
    "information",
    "investment",
    "market",
    "model_recommendations",
    "orders",
    "portfolio",
    "strategies",
    "strategy_recommendations",
]
